import './globals.css'
import { StateContext } from '@/context/StateContext'
import { Layout } from '@/components'
import { Toaster } from 'react-hot-toast';
export const metadata = {
  title: 'Ecommerce Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StateContext>
        <Layout>
          <Toaster />
        {children}
        </Layout>
        </StateContext>
        </body>
    </html>
  )
}
